### ISSUE TITLE
"TypeError: no implicit conversion of nil into Hash" when upgrading to Rails 5

### ISSUE THREAD

**Issue by fredngo** [ordinaryzelig/minispec-metadata#12]
Hello,

After upgrading to Rails 5, I am seeing "TypeError: no implicit conversion of nil into Hash" error messages.

I traced the error to this line - https://github.com/ordinaryzelig/minispec-metadata/blob/master/lib/minispec-metadata/describe.rb#L37:

`super_describe_metadata.merge(@describe_metadata)`

So `@describe_metadata` is `nil` at times. If I change this line to:

`super_describe_metadata.merge(@describe_metadata || {})`

then the error does not appear.

I'll put the fix in a Pull Request.

**Comment by ordinaryzelig** [comment]
What version of ruby, minispec-metadata, minitest, and rails are you using? I tried to reproduce your error but couldn't get it to pop up. Here's what I'm using:

ruby 2.4.0
minispec-metadata 3.2.1
minitest 5.10.1
rails 5.1.0

Any chance you could make a blank rails app and reproduce it for me?

**Comment by fredngo** [comment]
@ordinaryzelig I'll try!

**Comment by fredngo** [comment]
Hey @ordinaryzelig, finally I've been able to isolate and reproduce the error in a minimal Rails app.

https://github.com/fredngo/minispec-metadata-issue-12

Sorry that it took a while, this was extracted from a very large codebase. I've made the Rails app as tiny as possible in order to make it as easy as possible for you to take a look.

I've added you as a collaborator on that repo.

I've left all the details you need in order to reproduce the error in [the README file](https://github.com/fredngo/minispec-metadata-issue-12/blob/master/README.md).

Let me know what you think!

**Comment by ordinaryzelig** [comment]
Awesome! Thanks for taking the time to do that. Huge help. I'll take a look soon.

**Comment by ordinaryzelig** [comment]
@fredngo released new version. I tried it locally with the repo that you created, and it worked. Give it a try and let me know if it works for you too.

**Comment by fredngo** [comment]
Awesome, will try soon!

**Comment by fredngo** [comment]
It works for me, time to close this up. Thanks @ordinaryzelig !

**Comment by ordinaryzelig** [comment]
Great. Thank you too.
